on:
  #push:
  workflow_dispatch:
    inputs:
       choices:
         type: choice
         description: Please select the Environment where you want to deploy
         options:
         - DEV
         - QA
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  testing:
    name: Run Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      
  GB:
    needs: testing
    name: UK site
    runs-on: ubuntu-latest
    
    steps:
      - name: echo dev
        run: |
          echo "this is for dev gb"
