on:
  #push:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true
      Tags: 
         description: 'GENX_*/*'
         required: true
 
env:
  class: ${{secrets.CLASS}}
  name: ${{vars.name}}
jobs:  
  Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    if: ${{github.event.inputs.environment == tags == 'true'}}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run:
          echo "from ${{ inputs.Deploy-to }} environment"
          echo "${{env.class}}"
          echo "${{env.name}}   
