on:
  #push:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true
      Tags: 
         description: 'GENX_*/*'
         required: true
 # workflow_dispatch:
   # inputs:
    #   choices:
     #    type: choice
      #   description: Please select the Environment where you want to deploy
       #  options:
        # - DEV
         #- QA
  
jobs:  
  Build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.Deploy-to }}
    if: ${{github.event.inputs.tags == 'true'}}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
