name: Deletion of release versions
on:
  push:
  workflow_dispatch:

jobs:
  deletion-of-tags:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: delete
      run: |
          git tag | xargs git tag -d
          
