name: delete release versions
on:
  push:
#  workflow_dispatch:

env:
    Bearer_TOKEN: ${{ secrets.BEARERTOKEN }}  

jobs:
  delete-releases:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: deletion of Releases
      run: |
        curl -L \
        curl -H 'Authorization: Bearer_TOKEN' --url= "https://api.github.com/repos/madhu-us/MULTI-SITE"
        git for-each-ref --sort=taggerdate --format '%(refname:short) %(taggerdate:raw)' refs/releases | awk '$2 < '$(date -d '30 days ago' +%s)'' | cut -d ' ' -f 1 | xargs -I {} git releases -d {} && git push origin --delete {}
