name: Deletion of release versions
on:
  push:
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}  

jobs:
  deletion-of-tags:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: delete
      run: |
          gh release delete GENX_QA_SP49_15Sep23/uk1.3
          --cleanup-tag
          -y
          
