name: Deletion of release versions
on:
  push:
  workflow_dispatch:

env:
    Bearer_TOKEN: ${{ screats.bearertoken }}  

jobs:
  deletion-of-tags:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: delete
      run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/OWNER/REPO/releases
