name: delete release versions
on:
  push:
#  workflow_dispatch:

env:
    Bearer_TOKEN: ${{ secrets.BEARERTOKEN }}  

jobs:
  delete-releases:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: deletion of Releases
      run: |       
         
         export GIT_ASKPASS="echo Bearer_TOKEN"  # Replace $TOKEN with your actual token
         git fetch --prune --tags
         git push -u origin tags

         # Or git 2.37 Q2 2022+
         git config --global push.autoSetupRemote true
         git push
         git for-each-ref --sort=taggerdate --format '%(refname:short) %(taggerdate:raw)' refs/tags | awk '$2 < '$(date -d '60 days ago' +%s)''{} | cut -d ' ' -f 1 | xargs -I {origin/tags} git tag -d {origin/tags} && git push origin --delete {origin/tags}
