name: Deletion of release versions
on:
  push:
  workflow_dispatch:

env:
    GH_TOKEN: ${{ github.token }}  

jobs:
  deletion-of-tags:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: delete
      run: |
          git for-each-ref --sort=taggerdate --format '%(refname:short) %(taggerdate:raw)' refs/releases | awk '$2 < '$(date -d '20 days ago' +%s)'' | cut -d ' ' -f 1 | xargs -I {} git releases -d {} && git push origin --delete {}
          
