name: delete release versions
on:
  push:
#  workflow_dispatch:

env:
    Bearer_TOKEN: ${{ secrets.BEARERTOKEN }}  

jobs:
  ref:
    runs-on: ubuntu-latest
    steps:
      - name: tag
        run:  echo "Github Ref = ${{ github.ref }}"
              echo "Github Ref Name = ${{ github.ref_name }}"
  delete-releases:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: deletion of Releases
      run: |       
         
         export GIT_ASKPASS="echo Bearer_TOKEN"  # Replace $TOKEN with your actual token
         git fetch --prune --tags
         git push -u origin --tags

         # Or git 2.37 Q2 2022+
         git config --global push.autoSetupRemote true
         git push
         git for-each-ref --sort=taggerdate --format '%(refname:short) %(taggerdate:raw)' refs/tags | awk '$2 < '$(date -d '60 days ago' +%s)''{} > tags-list.txt

    - name: Create Artifact
      uses: actions/upload-artifact@v2
      with:
        name: branch-list
        path: branch-list.txt    
   
    - name: deleting tags
      run: |
         
         cut -d ' ' -f 1 | refs/tags xargs -I {} git tag -d {} && git push origin --delete {}
