name: Deployments

on:
  push:
    branches: ['v*.*.*']

jobs:
  make_release:
    if: github.ref_type == 'branch'
    name: Deploy ${{ github.ref_name }}
    environment: release
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        run: |
          echo "Deployment for branch ${{ github.ref_name }} goes here" >> "$GITHUB_STEP_SUMMARY"
