name: IE-Multi-env in Multi-site
on:
 # push:
  workflow_call:
     inputs:
       NAME:
     #  PATH:
         required: true
         type: string
     secrets:
       CLASS: 
      # IE_SECRET: 
         required: true 
env:
  path: ${{ vars.PATH }}
  
jobs:
  Ireland:
    #reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
    - uses: actions/checkout@v3
      with:
        class: ${{ secrets.CLASS }}
        name: ${{ inputs.NAME }}
        path: ${{ env.path }}
