name: IE-Multi-env in Multi-site
on:
 # push:
  workflow_call:
     inputs:
       NAME:
         required: true
         type: string
     secrets:
       CLASS:
         required: true 
        
env:
   name: ${{ vars.NAME }}
   school: ${{ secrets.CLASS }}
  
jobs:
  Ireland:
    #reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.CLASS }}
        configuration-path: ${{ inputs.NAME }}
