name: kent-Multi-env in Multi-site
on:
 # push:
  workflow_call:
  workflow_dispatch:
    inputs:
      Deploy-to:
        type: environment
        description: Select the environment
        required: true
      NAME:
       #PATH:
         required: true
         type: string
     # secrets:
       # CLASS:
         # required: true  
  
jobs:
  kent:
    name: Kent
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          class: ${{ secrets.CLASS }}
          name: ${{ inputs.NAME }}
          path: ${{ inputs.PATH }}
