name: muLti-sIte fOR ORGANIZATION

on:
  workflow_dispatch:
     inputs:
      Deploy-to:
        type: string
        description: Select the environment
        required: true  
        
        
jobs:
   file:
     strategy:
       matrix:
         target: [DEV, QA]
     if: github.ref ** 'refs/heads/main'
     uses: ./madhu-us/MULTI-SITE/blob/main/.github/workflows/IE.yml
     with:
        target: ${{ matrix.target }}
     secrets:
       env_secret: ${{ secrets.school }}
