Name: muLti-sIte fOR ORGANIZATION

on:
  workflow_dispacth:
        
        
job:
   file-1:
   if: github.ref ** 'refs/heads/main'
   uses: madhu-us/MULTI-SITE/blob/main/.github/workflows/IE.yml
   with:
      mul_env: DEV
  # secrets:
   #  env_secret: 
