name: muLti-sIte fOR ORGANIZATION

on:
  workflow_dispatch:
     inputs:
      Deploy-to:
        type: string
        description: Select the environment
        required: true  
        
        
jobs:
   file:
     
     #if: github.ref ** 'refs/heads/main'
     uses: ./.github/workflows/IE.yml
        
     secrets:
       env_secret: ${{ secrets.school }}
