name: muLti-sIte fOR ORGANIZATION

on:
  workflow_dispatch:
     inputs:
      Deploy-to:
        type: string
        description: Select the environment
        required: true  
        
        
jobs:
   Multi-IE:
     
     #if: github.ref ** 'refs/heads/main'
     uses: ./.github/workflows/IE.yml
        
     with:
       name: .github/IE.yml
     secrets:
       CLASS: ${{ secrets.CLASS }}
       
   Multi-kent:
     uses: ./.github/workflows/Kent.yml
     with:
       name: .github/Kent.yml
     secrets:
       CLASS: ${{ secrets.CLASS }}
        
       
       
