name: list of release versions
on:
  push:
  workflow_dispatch:

env:
    Bearer_TOKEN: ${{ secrets.BEARERTOKEN }}  

jobs:
  list-of-releases:
    runs-on: ubuntu-latest
    name: releases
    
    steps:
    - name: checkout
      uses: actions/checkout/@v3
         
   
    - name: List of Releases
      run: |
          curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/madhu-us/MULTI-SITE/releases
          
    - name: print test results
      working-directory: robot/tests
      run: cat report.html
