name: Manage release branch

on:
  release:
    types: [released]
  deployment_status:

jobs:
  create_release_branch:
    if: github.event_name == 'release' && github.event.release.draft == false  && github.event.release.prerelease == false
    name: Create release branch
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          
          git config user.name "madhu-us"
          git config user.email madhupole33@gmail.com
          git checkout -b ${{ github.ref_name }}
          git remote set-url origin https://${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin refs/heads/${{ github.ref_name }} && echo "Created release branch ${{ github.ref_name }}" >> "$GITHUB_STEP_SUMMARY"

  clean_up:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    name: Remove release branch
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          
          git config user.name "github actions"
          git config user.email actions@github.com
          git remote set-url origin https://${GH_TOKEN}@github.com/${{ github.repository }}
          git push origin :refs/heads/${{ github.event.deployment.ref }} && echo "Removed branch ${{ github.event.deployment.ref }}" >> "$GITHUB_STEP_SUMMARY"
