name: UAT Tagging

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'UAT Version'
        required: true

jobs:
  tag_uat_releases:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: main # Change to the branch where you want to run the workflow

    - name: Set up Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Create UAT Tags
      run: |
        regions=("uk" "kent" "ie")
        version=${{ github.event.inputs.version }}
        # GENX_UAT_SP49_26Aug23/uk1.23
        for region in "${regions[@]}"; do
          Releases_name="GENX_UAT_SP49_$(date +'%d%b%y')/${region}${version}"
          tag_name="GENX_UAT_SP49_$(date +'%d%b%y')/${region}${version}"
          git Releases $Releases_name
          git tag $tag_name
          git push origin $tag_name
        done
