name: Multi-env in Multi-site
on:
 # push:
  workflow_dispatch:
   inputs:
       choices:
         type: choice
         description: Please select the Environment where you want to deploy
         options:
         - DEV
         - QA 
       NodeValue:
         type: boolean
         description: "select Node web app"
         default: true 
       CMValue:
         type: boolean
         description: "select CM web app"
         default: false
       CDValue:
         type: boolean
         description: "select CD web app"
         default: false
env:
  name: ${{ vars.NAME }}
  secret: ${{ secrets.CLASS }}
  
jobs:
  uk:
    name: Run this Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
  deploy:
    needs: uk
    if: ${{ github.event.inputs.NodeValue == 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.choices }}
    #env: ${{ env.name }}  ${{ env.secret }}
         
    steps:
      - name: Setup checkout environment
        uses: actions/checkout@v3
        #runs-on: ubuntu-latest
      
       # token: 
          # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
          #cache: # optional, default is true
          # Used to specify the path to a dependency file - go.sum
         # cache-dependency-path: # optional
          # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
          #architecture: # optional
    
