name: Multi-env in Multi-site
on:
  push:
  workflow_dispatch:
  
jobs:
  required:
    name: Run this Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
